# Timing consistency
- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

# # Position of joints [ie. wheels] (published by ignition::gazebo::systems::JointStatePublisher)
# - ros_topic_name: '/joint_states'
#   gz_topic_name: '/model/husky/joint_states'
#   ros_type_name: 'sensor_msgs/msg/JointState'
#   gz_type_name: 'ignition.msgs.Model'
#   direction: GZ_TO_ROS

# # # Odometry (published by ignition::gazebo::systems::OdometryPublisher)
# - ros_topic_name: '/odometry'
#   gz_topic_name: '/model/husky/odometry'
#   ros_type_name: 'nav_msgs/msg/Odometry'
#   gz_type_name: 'ignition.msgs.Odometry'
#   direction: GZ_TO_ROS

# # Intertial Measurement Unit
# - ros_topic_name: '/imu'
#   gz_topic_name: '/model/husky/imu'
#   ros_type_name: 'sensor_msgs/msg/Imu'
#   gz_type_name: 'ignition.msgs.IMU'
#   direction: GZ_TO_ROS

# # Command velocity
# - ros_topic_name: '/cmd_vel'
#   gz_topic_name: '/model/husky/cmd_vel'
#   ros_type_name: 'geometry_msgs/msg/Twist'
#   gz_type_name: 'ignition.msgs.Twist'
#   direction: ROS_TO_GZ

# # Lidar: laserscan
# - ros_topic_name: "/scan"
#   gz_topic_name: "/model/husky/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# # Lidar: pointcloud
# - ros_topic_name: "/scan/points"
#   gz_topic_name: "/model/husky/scan/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "gz.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS

# # Camera: RGB
# - ros_topic_name: "/camera/image"
#   gz_topic_name: "/model/husky/camera/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: GZ_TO_ROS

# # Camera: depth
# - ros_topic_name: "/camera/depth/image"
#   gz_topic_name: "/model/husky/camera/depth_image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: GZ_TO_ROS

# # Camera: depth pointcloud
# - ros_topic_name: "/camera/depth/points"
#   gz_topic_name: "/model/husky/camera/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "ignition.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS

# DRONE TOPICS
# ============

# Drone Joint States
- ros_topic_name: '/drone/joint_states'
  gz_topic_name: '/model/sjtu_drone/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'ignition.msgs.Model'
  direction: GZ_TO_ROS

# Drone IMU
- ros_topic_name: '/drone/imu/out'
  gz_topic_name: '/model/sjtu_drone/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

# Drone Front Camera
- ros_topic_name: '/drone/front/image_raw'
  gz_topic_name: '/model/sjtu_drone/front_camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

# Drone Bottom Camera
- ros_topic_name: '/drone/bottom/image_raw'
  gz_topic_name: '/model/sjtu_drone/bottom_camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

# Drone Command Velocity
- ros_topic_name: '/drone/cmd_vel'
  gz_topic_name: '/model/sjtu_drone/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: ROS_TO_GZ

# Drone Takeoff Command
- ros_topic_name: '/drone/takeoff'
  gz_topic_name: '/model/sjtu_drone/takeoff'
  ros_type_name: 'std_msgs/msg/Empty'
  gz_type_name: 'ignition.msgs.Empty'
  direction: ROS_TO_GZ

# Drone Land Command
- ros_topic_name: '/drone/land'
  gz_topic_name: '/model/sjtu_drone/land'
  ros_type_name: 'std_msgs/msg/Empty'
  gz_type_name: 'ignition.msgs.Empty'
  direction: ROS_TO_GZ

# Drone Sonar
- ros_topic_name: '/drone/sonar/out'
  gz_topic_name: '/model/sjtu_drone/sonar'
  ros_type_name: 'sensor_msgs/msg/Range'
  gz_type_name: 'ignition.msgs.SonarRanged'
  direction: GZ_TO_ROS

  # Additional Drone Sensors
- ros_topic_name: '/drone/gps/nav'
  gz_topic_name: '/model/sjtu_drone/gps/nav'
  ros_type_name: 'sensor_msgs/msg/NavSatFix'
  gz_type_name: 'ignition.msgs.NavSat'
  direction: GZ_TO_ROS

- ros_topic_name: '/drone/gps/vel'
  gz_topic_name: '/model/sjtu_drone/gps/vel'
  ros_type_name: 'geometry_msgs/msg/TwistStamped'
  gz_type_name: 'ignition.msgs.Twist'
  direction: GZ_TO_ROS

# Additional Control Topics
- ros_topic_name: '/drone/posctrl'
  gz_topic_name: '/model/sjtu_drone/posctrl'
  ros_type_name: 'std_msgs/msg/Bool'
  gz_type_name: 'ignition.msgs.Boolean'
  direction: ROS_TO_GZ

- ros_topic_name: '/drone/dronevel_mode'
  gz_topic_name: '/model/sjtu_drone/dronevel_mode'
  ros_type_name: 'std_msgs/msg/Bool'
  gz_type_name: 'ignition.msgs.Boolean'
  direction: ROS_TO_GZ

- ros_topic_name: '/drone/reset'
  gz_topic_name: '/model/sjtu_drone/reset'
  ros_type_name: 'std_msgs/msg/Empty'
  gz_type_name: 'ignition.msgs.Empty'
  direction: ROS_TO_GZ

# Status Topics (these might be GZ_TO_ROS)
- ros_topic_name: '/drone/cmd_mode'
  gz_topic_name: '/model/sjtu_drone/cmd_mode'
  ros_type_name: 'std_msgs/msg/Bool'
  gz_type_name: 'ignition.msgs.Boolean'
  direction: GZ_TO_ROS

- ros_topic_name: '/drone/state'
  gz_topic_name: '/model/sjtu_drone/state'
  ros_type_name: 'std_msgs/msg/Int8'
  gz_type_name: 'ignition.msgs.Int32'
  direction: GZ_TO_ROS

# Ground Truth Topics
- ros_topic_name: '/drone/gt_acc'
  gz_topic_name: '/model/sjtu_drone/gt_acc'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: GZ_TO_ROS

- ros_topic_name: '/drone/gt_pose'
  gz_topic_name: '/model/sjtu_drone/gt_pose'
  ros_type_name: 'geometry_msgs/msg/Pose'
  gz_type_name: 'ignition.msgs.Pose'
  direction: GZ_TO_ROS

- ros_topic_name: '/drone/gt_vel'
  gz_topic_name: '/model/sjtu_drone/gt_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: GZ_TO_ROS