# Pre-planned waypoint routes for drone
# Each drone has a sequence of waypoints with position and timing information

waypoint_configs:
  rs1_drone_1:
    mission_name: "Move to Tree to Scan"
    waypoints:
      - position: {x: -18.99, y: 14.61, z: 15.63}
        dwell_time: 2.0
      - position: {x: -28.428900, y: -9.032370, z: 5.0}
        dwell_time: 2.0
      - position: {x: -20.554900, y: -5.113920, z: 5.0}
        dwell_time: 2.0
      - position: {x: -12.403400, y: 4.239570, z: 5.0}
        dwell_time: 2.0
      - position: {x: -8.494550, y: 11.878800, z: 5.0}
        dwell_time: 2.0
      - position: {x: -4.719600, y: 7.670240, z: 5.0}
        dwell_time: 2.0
      - position: {x: -7.236320, y: -0.491806, z: 5.0}
        dwell_time: 2.0
      - position: {x: -11.266300, y: -9.183030, z: 5.0}
        dwell_time: 2.0
        
mission_params:
  takeoff_altitude: 2.0
  landing_speed: 0.5
  waypoint_tolerance: 0.8
  max_velocity: 3.0
  loop_missions: true
  helipad_location:
    x: 0.0
    y: 0.0
    z: 0.0
